### PR TITLE
Several Improvements

### PR DESCRIPTION
**Pull request by gipi**
As anticipated in issue #1 here some improvements (don't merge yet this stuff let me try it in a my project before).

- [x] README with more info to get ready quickly
- [x] added template tags to setup and render license symbols
- [x] added tests to check correct behaviour (I don't know if there is more tests possible)
- [x] added ``tox`` configuration file to test app in different version of python/Django (minor issue with some tests in Django1.7 about templates).

Let me know if it's all ok, meanwhile I try to check if all is working as expected in a live system.

### CODE REVIEW

**Comment by rybesh** [comment]
Thanks! Did you have a chance yet to test if this works for you?

**Comment by gipi** [comment]
I haven't tried yet, maybe tomorrow, sorry for the delay.

**Comment by rybesh** [comment]
No worries! I'm not in a hurry… :smiley:

**Comment by gipi** [comment]
Finally I've tested in another project (Django1.8) and all seems to work.

**Comment by rybesh** [comment]
Thanks so much!

**Comment by gipi** [comment]
You are wellcome.

**Pull request merged**
